### ISSUE TITLE
新建侧边栏小工具报错

### ISSUE THREAD

**Issue by barryblueice** [xb2016/Kratos#521]
TypeError: Cannot read properties of undefined (reading 'get')
    at Ne._createWidget (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/customize-widgets.min.js:7:30146)
    at https://c0.wp.com/c/6.0.1/wp-includes/js/dist/customize-widgets.min.js:7:31231
    at Array.map (<anonymous>)
    at Ne._updateWidgets (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/customize-widgets.min.js:7:31137)
    at Ne.setWidgets (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/customize-widgets.min.js:7:31426)
    at https://c0.wp.com/c/6.0.1/wp-includes/js/dist/customize-widgets.min.js:7:17182
    at pt (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/vendor/react-dom.min.js:9:44204)
    at ht (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/vendor/react-dom.min.js:9:44658)
    at Object.useState (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/vendor/react-dom.min.js:9:107007)
    at e.useState (https://c0.wp.com/c/6.0.1/wp-includes/js/dist/vendor/react.min.js:9:10899)
切成其他主题就没有报错……

**Comment by barryblueice** [comment]
只要是新建一个页面，就会报错

**Comment by barryblueice** [comment]
已经找到原因了，打开Gutenberg 编辑器就会报错，关闭就不会报错。

**Comment by n0099** [comment]
可以复现

在启用gutenberg时使用新版的采用区块编辑器的`/wp-admin/widgets.php`随便插入一个区块（不是legacy widgets里的，其是禁用gutenberg时在`widgets.php`添加的那种旧版小工具）并保存就会导致
> There was an error. Cannot read properties of undefined (reading 'hasOwnProperty')

![image](https://user-images.githubusercontent.com/13030387/194608517-4393f7fb-aad5-4a7b-8f98-779482d6616f.png)
`/wp-includes/js/dist/edit-widgets.min.js`：![image](https://user-images.githubusercontent.com/13030387/194608882-ebceced3-44b9-44fb-a255-19a4468bca20.png)


![image](https://user-images.githubusercontent.com/13030387/194614074-c84326b4-6a50-4271-8518-7dba96532207.png)
本质上是因为`/wp-json/batch/v1`的后端返回了http400 `The provided widget type (id_base) cannot be updated.`错误
![image](https://user-images.githubusercontent.com/13030387/194609654-24f2707c-7924-411b-b3a8-e822c3091040.png)


这个错误来自
https://core.trac.wordpress.org/browser/tags/6.0.2/src/wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php#L552

**Comment by n0099** [comment]
罪魁祸首找到了：https://github.com/seatonjiang/kratos/blob/dc88428c960dcfa77fc7ad7ef0fb59203e0732a4/inc/theme-widgets.php#L37-L56
https://developer.wordpress.org/reference/classes/wp_widget_block/

**Comment by seatonjiang** [comment]
这个问题已经修复了，由于在经典模式禁用了WP_Widget_Block，所以在古登堡模式会出异常，更新主题版本即可修复。
<img width="372" alt="image" src="https://user-images.githubusercontent.com/57834639/204132725-620f07ec-15a7-4360-a4ac-cb5c2e6729fb.png">
