### ISSUE TITLE
主题上传后启动失败

### ISSUE THREAD

**Issue by CoffeeHi** [xb2016/Kratos#581]
```
Fatal error: Uncaught Error: Call to undefined function wp_date() in /usr/share/wordpress/wp-content/themes/kratos-4.1.6/inc/theme-options.php:1071 Stack trace: #0 /usr/share/wordpress/wp-content/themes/kratos-4.1.6/inc/codestar-framework/autoload.php(23): require() #1 /usr/share/wordpress/wp-content/themes/kratos-4.1.6/functions.php(16): require('/usr/share/word...') #2 /usr/share/wordpress/wp-settings.php(479): include('/usr/share/word...') #3 /etc/wordpress/wp-config.php(108): require_once('/usr/share/word...') #4 /usr/share/wordpress/wp-load.php(37): require_once('/etc/wordpress/...') #5 /usr/share/wordpress/wp-admin/admin.php(34): require_once('/usr/share/word...') #6 /usr/share/wordpress/wp-admin/customize.php(13): require_once('/usr/share/word...') #7 {main} thrown in /usr/share/wordpress/wp-content/themes/kratos-4.1.6/inc/theme-options.php on line 1071
```

Env:
PHP 7.2.34
wordpress-5.1.15-1.el7.noarch
Centos7_64

**Comment by n0099** [comment]
您没套```结果把一堆`#1~#7`都给refer了

**Comment by seatonjiang** [comment]
wp_date 函数最低的 WP 版本要求是 5.3

**Comment by n0099** [comment]
> Env:
> PHP 7.2.34
> wordpress-5.1.15-1.el7.noarch
> Centos7_64

所以阁下的这套环境早就全都EOL了：
https://endoflife.date/php
https://endoflife.date/wordpress
https://endoflife.date/centos

**Comment by CoffeeHi** [comment]
@n0099 @seatonjiang 小白第一次部署wordpress，多谢😄
